<?php
defined('BASEPATH') or exit('No direct script access allowed'); ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Agrawal Public School | School in Deoria</title>
  <meta property="og:title" content="Agrawal Public School | School in Deoria" />
  <meta property="og:site_name" content="Agrawal Public School" />
  <meta property="og:url" content="https://www.apsdeoria.com" />
  <meta property="og:description" content="School in Deoria. Welcome to the new school of thoughts and excellence." />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="https://www.apsdeoria.com/aps/bootstrap/img/slider_5.jpg" />
  <meta property="og:image" content="https://www.apsdeoria.com/aps/bootstrap/img/aps_logo.png" />
  <meta property="og:image" content="https://www.apsdeoria.com/aps/bootstrap/img/slider_6.jpg" />
  <meta property="og:image" content="https://www.apsdeoria.com/aps/bootstrap/img/slider_7.jpg" />
  <meta property="og:image" content="https://www.apsdeoria.com/aps/bootstrap/img/slider_8.jpg" />
  <meta property="og:image:alt" content="APS Students" />
  <meta property="og:video" content="https://www.youtube.com/watch?v=B14dnnDZi2o" />
  <meta name="description" content="Agrawal Public School | School in Deoria | Welcome To The New School Of Thoughts. Admission Open For 2020-2021 | Play Group - Class VIII" />
  <meta name="keywords" content="School, Education, Admission Open, Play-Group, LKG, UKG, APS, Deoria, Public School" />
  <meta name="author" content="Shubham Agrawal" />
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo base_url(); ?>aps/bootstrap/img/aps_logo.png">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,700|Open+Sans" rel="stylesheet">
  <link rel="stylesheet" href="<?php echo base_url(); ?>aps/bootstrap/css/styles-merged.css">
  <link rel="stylesheet" href="<?php echo base_url(); ?>aps/bootstrap/css/style.min.css">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135429012-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-135429012-1');
  </script>

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "EducationalOrganization",
      "name": "Agrawal Public School",
      "address": {
        "@type": "PostalAddress",
        "addressCountry": "IN",
        "addressLocality": "Deoria",
        "addressRegion": "Uttar Pradesh",
        "postalCode": "274001",
        "streetAddress": "New Colony Near Shiv Mandir, Deoria U.P",
        "telephone": "+91-9454549454",
        "description": "Welcome to the new school of thoughts and excellence"
      },
      "areaServed": "Deoria",
      "@id": "https://www.apsdeoria.com/",
      "url": "https://www.apsdeoria.com/",
      "logo": "https://www.apsdeoria.com/aps/bootstrap/img/aps_logo.png",
      "email": "contact@apsdeoria.com",
      "sameAs": [
        "https://www.facebook.com/apsdeoria",
        "https://twitter.com/apsdeoria",
        "https://www.instagram.com/apsdeoria",
        "https://www.linkedin.com/in/apsdeoria",
        "https://www.youtube.com/channel/UCqWRbnwa38SUG3fdBZjh7oQ"
      ]
    }
  </script>

  <!-- Webmaster -->
  <meta name="google-site-verification" content="gZzIh9zhl6469SzYIChbLcWbKzeUzfyBvVrBkeJWnfc" />

</head>

<body>

  <div class="probootstrap-search" id="probootstrap-search">
    <a href="#" class="probootstrap-close js-probootstrap-close"><i class="icon-cross"></i></a>
    <form action="#">
      <input type="search" name="s" id="search" placeholder="Search a keyword and hit enter...">
    </form>
  </div>

  <div class="probootstrap-page-wrapper">
    <!-- Fixed navbar -->

    <div class="probootstrap-header-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 col-md-9 col-sm-9 probootstrap-top-quick-contact-info">
            <span><i class="icon-location2"></i><a href="https://maps.app.goo.gl/mv1dX" target="_blank">New Colony Near
                Shiv Mandir, Deoria U.P</a></span>
            <span><i class="icon-phone2"></i><a href="tel:9454549454">+91-9454549454</a></span>
            <span><i class="icon-mail"></i><a href="mailto: contact@apsdeoria.com">conatct@apsdeoria.com</a></span>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-3 probootstrap-top-social">
            <ul>
              <li><a href="https://twitter.com/apsdeoria" target="_blank"><i class="icon-twitter"></i></a></li>
              <li><a href="https://www.facebook.com/apsdeoria" target="_blank"><i class="icon-facebook2"></i></a></li>
              <li><a href="https://www.instagram.com/apsdeoria" target="_blank"><i class="icon-instagram2"></i></a></li>
              <li><a href="https://www.youtube.com/channel/UCqWRbnwa38SUG3fdBZjh7oQ" target="_blank"><i class="icon-youtube"></i></a></li>
              <li><a href="https://www.linkedin.com/in/apsdeoria/" target="_blank"><i class="icon-linkedin"></i></a></li>
              <li><a href="#" class="probootstrap-search-icon js-probootstrap-search"><i class="icon-search"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-default probootstrap-navbar">
      <div class="container">
        <div class="navbar-header">
          <div class="btn-more js-btn-more visible-xs">
            <a href="#"><i class="icon-dots-three-vertical "></i></a>
          </div>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo base_url(); ?>" title="Welcome:APS">Agrawal Public School</a>
        </div>

        <div id="navbar-collapse" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo base_url(); ?>">Home</a></li> <!-- TODO li class="active" -->
            <li><a href="<?php echo base_url() . 'admission'; ?>">Admission</a></li>
            <li><a href="<?php echo base_url() . 'about'; ?>">About Us</a></li>
            <li><a href="<?php echo base_url() . 'events'; ?>">Events</a></li>
            <li><a href="<?php echo base_url() . 'contact'; ?>">Contact</a></li>
            <li><a href="<?php echo base_url() . 'gallery'; ?>">Gallery</a></li>
          </ul>
        </div>
      </div>
    </nav>